name: Build and Release KeyCatcher (Windows + Android)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    name: Build Windows and Android

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install MAUI workloads
        run: dotnet workload install maui

      - name: Restore dependencies
        run: dotnet restore src/client/KeyCatcher/KeyCatcher2.csproj

      # ---------- Build Windows ----------
      - name: Build Windows (Unpackaged EXE)
        run: >
          dotnet publish src/client/KeyCatcher/KeyCatcher2.csproj
          -f net9.0-windows10.0.19041.0
          -c Release
          -p:WindowsPackageType=None
          -p:Platform="Any CPU"

      # Auto-detect and zip publish folder
      - name: Zip Windows output (auto-detect)
        shell: pwsh
        run: |
          $publishPath = Get-ChildItem -Path "src/client/KeyCatcher/bin/Release/net9.0-windows10.0.19041.0" -Directory -Recurse |
            Where-Object { $_.Name -eq "publish" } |
            Select-Object -First 1
          if (-not $publishPath) { throw "Publish folder not found!" }
          Write-Host "Found publish folder: $($publishPath.FullName)"
          Compress-Archive -Path "$($publishPath.FullName)\*" `
                           -DestinationPath "src/client/KeyCatcher/bin/Release/net9.0-windows10.0.19041.0/KeyCatcher_Windows.zip"

      # ---------- Build Android ----------
      - name: Build Android APK
        run: >
          dotnet publish src/client/KeyCatcher/KeyCatcher2.csproj
          -f net9.0-android
          -c Release
          -p:AndroidPackageFormat=apk
          -p:AndroidKeyStore=false

      # ---------- Upload Artifacts ----------
      - name: Upload Windows ZIP
        uses: actions/upload-artifact@v4
        with:
          name: KeyCatcher-Windows
          path: src/client/KeyCatcher/bin/Release/net9.0-windows10.0.19041.0/KeyCatcher_Windows.zip

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: KeyCatcher-Android
          path: src/client/KeyCatcher/bin/Release/net9.0-android/publish/*.apk

  # ---------- GitHub Release ----------
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/KeyCatcher-Windows/KeyCatcher_Windows.zip
            artifacts/KeyCatcher-Android/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}