name: Build Android APK
on:
  push:
    tags:
      - "v*"

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Install MAUI workload
        run: |
          dotnet workload install maui-android

      - name: Restore
        run: dotnet restore src/client/KeyCatcher/KeyCatcher2.sln

      - name: Decode keystore
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        run: |
          echo "${ANDROID_KEYSTORE_BASE64}" | base64 -d > my.keystore
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Build APK signed if keystore present else unsigned
        run: |
          if [ -f my.keystore ]; then
            dotnet publish src/client/KeyCatcher/YourApp.csproj \
              -c Release \
              -f net8.0-android \
              -p:AndroidPackageFormat=apk \
              -p:AndroidKeyStore=True \
              -p:AndroidSigningKeyStore=my.keystore \
              -p:AndroidSigningStorePass=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
              -p:AndroidSigningKeyAlias=${{ secrets.ANDROID_KEY_ALIAS }} \
              -p:AndroidSigningKeyPass=${{ secrets.ANDROID_KEY_PASSWORD }} \
              -p:PublishDir=${{ github.workspace }}/artifacts/android/
          else
            dotnet publish src/YourApp.csproj \
              -c Release \
              -f net8.0-android \
              -p:AndroidPackageFormat=apk \
              -p:PublishDir=${{ github.workspace }}/artifacts/android/
          fi

      - name: Find APK
        run: |
          APK_PATH=$(find "${GITHUB_WORKSPACE}/artifacts/android" -name "*.apk" | head -n 1)
          if [ -z "$APK_PATH" ]; then
            echo "No APK found"
            exit 1
          fi
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ${{ env.APK_PATH }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.APK_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}